Fix hdCycles crash on updating volumes PT-835
tangent-opensource/hdcycles pull request #117
Opened 2021-03-25 19:05 UTC by sergeneren

Added a function to update the openvdb grid of the "HdCyclesVolumeLoader", which is cleared by the cycles "device_load_image" function. This grid is needed for constructing a mesh and was causing a crash when volumes are updated. 

Fixes PT-835

Testing procedure:

* Download the test file
* Render in viewport with cycles
* Disable transform and render a second time, HdCycles shouldn't crash anymore.

[test file](https://github.com/tangent-opensource/hdcycles/files/6207197/volume_update.zip)

2021-03-25 21:44 UTC, bareya commented on plugin/hdCycles/openvdb_asset.h
> +        } catch (const openvdb::IoError& e) {
I would improve here:
*  We could use `TF_ ` library to report those type of errors. 
* The verbosity of the message also could be improved. Filename should be included in the error message.
* Can UpdateGrid return any other exception that `IoError`? If so that should be handled as well.

2021-03-26 14:50 UTC, skwerner requested changes
Looks good to me. If you add the logging/exception handling changes that Piotr mentioned, we can merge it.

2021-03-26 15:52 UTC, sergeneren commented
Thanks for the review. 

Today I discovered that this pr doesn't cover the event when multiple volumes in a scene have different dirty states. If one of the volumes have a clean state the grid won't be updated and hdCycles will still crash. I am trying to come up with another solution.

2021-03-26 21:24 UTC, sergeneren commented
I've added an override to the VDBImageLoader class' cleanup function to retain the openvdb grid. This way we don't lose it during the mesh build time. I've tested it with a couple vdb files over a span of an hour and haven't seen a crash. It should be in good position now.

2021-03-26 22:02 UTC, bareya approved these changes

2021-03-29 22:38 UTC, merged