Refining how lights work in hdCycles
tangent-opensource/hdcycles pull request #49
Opened 2021-01-22 02:15 UTC by boberfly

- Parameter changes on-sync will re-create a new shader graph and be applied via set_graph() calls
- As a result, removed excess shader member pointers they are not needed & prevents crashes
- Added support for textures on rect/quad lights (TODO: need to check if texture co-ords are consistent with other delegates)
- Fixed HDRI co-ordinates on dome/background lights (matches Houdini GL)

2021-01-24 19:25 UTC, Vochsel requested changes
Built locally and works great. If possible an environment variable for up axis with the default to Z (Blender) would be the best course of action. Internally we can set to Y, however I think it's best to keep the default behaviour of this repo to match Blender USD exports. I can't find any way to get the up axis from Hydra, so env var is probably the only way to go.

The default hydra behaviour with "Default dome lights" seems to be that with no lights present, a gray dome light is used, but once any light (dome or otherwise) is added, the default light is removed. We partially had this functionality before (I think it broke some time ago, and now a dome light is required if you want to disable it). Not sure if you have the time to check this in this PR, perhaps we can create another PR soon to fix this.

Changes:
 * ENV var toggle for up axis behaviour
 * Maybe fix the default dome light not being removed (Optional)

Thanks for your work, really appreciated. Cheers!

2021-01-24 22:44 UTC, boberfly commented on plugin/hdCycles/light.cpp
> +            backroundNode->strength = m_finalIntensity;
Actually on any param change there's a whole new/delete being done for any light, the HdDirtyBits for lights isn't fine-grained enough to prevent that, however I am making my own for the different combination states that the shader graph could get into and only re-creating if they don't match...

2021-01-24 22:45 UTC, boberfly commented on plugin/hdCycles/light.cpp
> +                        ccl::make_float3(0.0f, 0.0f, M_PI * -0.5f);
Any preference on the environment variable name?

2021-01-24 22:45 UTC, boberfly commented on plugin/hdCycles/light.cpp
> +                if (filepath != "") {
Sure

2021-01-25 15:49 UTC, Vochsel commented on plugin/hdCycles/light.cpp
> +                        ccl::make_float3(0.0f, 0.0f, M_PI * -0.5f);
I'm tempted to say `HD_CYCLES_UP_AXIS` and use chars `Y` or `Z` for readability, with the sacrifice of a char comparison (potentially 2 if we add support for negative e.g. "-Z"). 

Most places have access to the HdCyclesRenderParam. Perhaps we could check once there and setup an enum. And use that everywhere. 

In saying that, I'm really not sure how many up axis' we need to think about supporting. 

I'm also just as happy for now have a var like `HD_CYCLES_UP_AXIS_Y` and setting default to false. 

Happy with either for now. Whatever you think is best/easiest.

2021-01-25 15:50 UTC, Vochsel commented on plugin/hdCycles/light.cpp
> +            backroundNode->strength = m_finalIntensity;
Yeah thats the same for almost all prims. That sounds like a good call.

2021-01-25 15:51 UTC, Vochsel commented on plugin/hdCycles/light.cpp
> +            backroundNode->strength = m_finalIntensity;
I wonder/hope if the new Cycles API is smart enough to detect changes on this granular level too. Would make our end easier

2021-01-25 17:05 UTC, boberfly commented on plugin/hdCycles/light.cpp
> +                        ccl::make_float3(0.0f, 0.0f, M_PI * -0.5f);
Can we cache it somewhere as an enum, like on the delegate itself? An uint8_t is fine to store all the different combinations.

2021-01-25 17:08 UTC, boberfly commented on plugin/hdCycles/light.cpp
> +            backroundNode->strength = m_finalIntensity;
We can always make Cycles API PRs to help our cause I'd imagine. I am still keen on making a pure C-API so that Cycles and be a shared lib and hides all of its dependencies from other libraries from needing them as well like hdCycles/GafferCycles...

2021-01-25 20:13 UTC, boberfly commented on plugin/hdCycles/light.cpp
> +            backroundNode->strength = m_finalIntensity;
Partially resolved, I found this to be error-prone due to folding of graphs for optimisation, which means the node doesn't exist after Cycles gets it (eg. the output value is baked into emission's input).

2021-01-26 19:43 UTC, Vochsel approved these changes
Looks solid, thanks for that up axis change.

2021-01-28 21:21 UTC, merged