Support for FaceVarying and Uniform normals
tangent-opensource/hdcycles pull request #51
Opened 2021-02-02 22:34 UTC by dedoardo

Adding support for mesh normals with FaceVarying and Uniform interpolation by setting them as corner attributes in the Cycles mesh.  This [PR](https://github.com/tangent-opensource/cycles/pull/3) is required.

Allowing normals to be specified on subdivision surfaces (Cycles side) requires filling in different arrays. I don't know if we want to pursue this direction or adhere to the USD guidelines more strictly.

2021-02-03 16:51 UTC, Vochsel requested changes
Overall looks good. There is an issue with leftHanded vertex normals but this will hopefully be solved with @bareya's work. 

Please also format this with a clang formatter if possible.

If we can use ccl::ATTR_STD_FACE_NORMAL for HdInterpolationUniform, I would have thought that preferrable, but I might be missing something on the cycles side.

The notes about performance and moving leftHanded branch to a multiplication is me thinking out loud. These changes are not necessary imo.  

Required changes:
 * formatting
 * maybe switch to face normals
 * maybe remove if statement from for loops and use a multiplication instead

2021-02-03 16:51 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +            }
A profiler may show more info, and this might be redundant, but perhaps setting a scale outside of this for loop with direction, and then multiplying all conversions by the scale might be faster? 

```
float scale = (m_orientation == HdTokens->leftHanded) ? -1.0f : 1.0f;

for (int i = 0; i < m_faceVertexCounts.size(); i++) {
            const int vCount = m_faceVertexCounts[i];	 
            ccl::float3 fNi = vec3f_to_float3(normals[i]) * scale;
            
```

2021-02-03 16:51 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +            }
This is more me thinking out loud.

2021-02-03 16:51 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +        ccl::Attribute* attr_fvN = attributes.add(ccl::ATTR_STD_CORNER_NORMAL);
Can't we use ccl::ATTR_STD_FACE_NORMAL, and save us the data?

2021-02-03 16:51 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +                }
if we can use `ccl::ATTR_STD_FACE_NORMAL` this becomes less data

2021-02-03 16:51 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +              sceneDelegate->GetPrimvarDescriptors(id, HdInterpolationUniform) },
I also added this in my Attribute PR, should be noted when merging these PRS

2021-02-03 16:51 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +                    fvN[i * 3 + j] = -fvN[i * 3 + j];
Again, maybe we can save the branching and just multiply by a scale, but I also have not tested the performance of this.

2021-02-03 16:51 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +            }
@boberfly @bareya might have done this before

2021-02-03 16:59 UTC, boberfly commented on plugin/hdCycles/mesh.cpp
> +            }
I think in cortex/gaffer they seemed to just match so I didn't need to deal with handedness (USD scene reader seems to fix it up on-read).

2021-02-03 16:59 UTC, bareya commented on plugin/hdCycles/mesh.cpp
> +            }
@Vochsel you are right, branching should be pull out from the for loop. This is how it's done in PxOsd.

2021-02-03 17:01 UTC, boberfly commented
I wanted to add here that MikkTspace stuff will need looking at also for hdCycles (see note of it in the cycles PR):
https://github.com/tangent-opensource/cycles/pull/3

I think if a normal map is used on faceVarying normals it'll crash currently, so it'll need looking into to do the right thing when creating tangents/bi-tangents.

2021-02-03 17:59 UTC, dedoardo commented
Addressed the formatting and the flipping outside the loop. 

Regarding custom face normals, unless I am totally wrong, Cycles does not really support them. [The geometric normal is computed when the ray hits the surface using the triangle points](https://github.com/tangent-opensource/cycles/blob/master/src/kernel/kernel_shader.h#L95) and used as shading normal unless vertex normals are present. Essentially, it won't do anything with `ATTR_STD_FACE_NORMAL`. 

The good news is that corner normals in Cycles put the machinery in place to have different types of normals per object. This requires deciding how to expose which types of normal are to be used because now we would have 3 different types rather than 2. 
An order of precedence would work but it's a bit hidden and could run into issues as the geometry code is keen on recomputing normals. @skwerner do you have any thoughts on what's a reasonable way to proceed?

Once that is discussed it shouldn't be too hard to include it in Cycles in the same corner PR or have a separate one for it.

2021-02-03 18:10 UTC, dedoardo commented
@boberfly The tangent space calculation is a good point. I don't think it will crash, but will produce wrong results as it will use the vertex normals rather than the custom ones (corner or face). 
It can be addressed, I need to create a scene with normal mapping and see what happens.

2021-02-04 16:59 UTC, Vochsel approved these changes
Code here looks good. Strange situation with ATTR_STD_FACE_NORMAL, but I'll take your word for it, your solution seems good. Will the tangent fix @boberfly mentioned will be part of this PR or another? If not, this looks good to approve, but is held by the Cycles PR

2021-02-04 16:59 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +        ccl::Attribute* attr_fvN = attributes.add(ccl::ATTR_STD_CORNER_NORMAL);
Thanks for the clarification about this. If @skwerner has no other thoughts, this seems like a reasonable solution.

2021-02-04 16:59 UTC, Vochsel commented on plugin/hdCycles/mesh.cpp
> +            }
Thanks for this fix in the latest push @dedoardo :)

2021-02-05 18:50 UTC, dedoardo commented
The mikktspace callbacks now use corner normals over vertex/face when present. The code that computes the tangents has been moved out of the attributes loop to guarantee that the correct normals are available.

I tested it on a couple of meshes with normal mapping and it seems to not break anything.

2021-03-09 00:51 UTC, merged