WIP: Adding triangulation and OpenSubdiv refinment
tangent-opensource/hdcycles pull request #67
Opened 2021-02-05 17:54 UTC by bareya

This is very heavy work in progress.

2021-03-05 22:23 UTC, dedoardo requested changes
Really great job all round, both refactoring and supporting all the features!!

From a couple of tests it seems to work. I left some minor comments around, I am not too familiar with the OpenSubdiv API, maybe someone else can give better advice on that end, but as long as nothing else is broken, we should look to merge this soon.

Two extra comments

- _PopulateMotion needs to be called somewhere
- Honestly, I do not understand the behavior of the color attribute in Column 3 (4 a bit more). Why is the bottom patch so different than the top one in the central 4 squares? I'm guessing that the non-squared boundary mean that they are creases? Still, the interpolation seems a bit weird... Although it's true that you can't see the per-vertex values.

2021-03-05 22:23 UTC, dedoardo commented on plugin/hdCycles/mesh.cpp
> +    static std::mutex material_mutex;
Why static and not a member?

2021-03-06 23:54 UTC, bareya commented on plugin/hdCycles/mesh.cpp
> +    static std::mutex material_mutex;
This is a left over from me trying to find out why the code was crashing. Definitely that mutex should be a member. Good find!

2021-03-10 22:55 UTC, dedoardo commented
I have merged dev into the current branch, things seem to work fine except for deformation blur which behaves erratically and crashes, it's thus commented out right now. 
Found two bugs along the way
- The interpolation type for the normals was not initialized/set and resulted in normals not being read.
- There was a mismatch between the normal interpolation type and the refiner method that was being called. The implementations look the same, so I don't think this was causing any issues.

2021-03-10 23:04 UTC, bareya commented on plugin/hdCycles/mesh.cpp
> +    display_style.refineLevel = 5;
Has this been removed?

2021-03-11 02:23 UTC, bareya commented on plugin/hdCycles/mesh.cpp
> +        _UpdateObject(scene, param, dirtyBits, false);
Super cool that you remembered about this one :+1:

2021-03-11 02:25 UTC, bareya commented
> * The interpolation type for the normals was not initialized/set and resulted in normals not being read.

@dedoardo Can you point to the code please, I don't see it.

2021-03-11 05:52 UTC, dedoardo commented
[Here](https://github.com/tangent-opensource/hdcycles/blob/430134fa5c7b7ae89665cbfaec4d413ceae5c247/plugin/hdCycles/mesh.cpp#L455), the interpolation should be set to the index in the loop, but remains initialized although the function returns true.

2021-03-15 14:45 UTC, dedoardo commented
I have reverted the behavior of scene locks to match the one in `dev`, unfortunately I don't think we cannot get rid of the scene locks when editing cycles objects but [we should look to be smarter about their usage](https://github.com/tangent-opensource/hdcycles/issues/89). 
Excluding this, I think this PR is pretty much ready to go. We might want to merge [the normal fix](https://github.com/tangent-opensource/hdcycles/pull/88) before or right after merging this PR as it fixed shading issues in time varying geometry.

2021-03-15 14:46 UTC, dedoardo approved these changes

2021-03-15 14:50 UTC, skwerner requested changes

2021-03-15 14:50 UTC, skwerner commented on .clang-format
> +ColumnLimit:     120
This is unrelated to mesh and OSD, I think this would be better as a separate PR.

2021-03-15 14:50 UTC, skwerner commented on plugin/hdCycles/meshRefiner.cpp
> +#include <opensubdiv/osd/tbbEvaluator.h>
We don't have tbbEvaluator available in our build variants 0 and 1 (that is, building against our own OSD Rez packages instead of Houdini's).

__has_include() could be an option to use TBB where available (with a cpuEvaluator.h fallback) if we move up to C++17.

For now, I'd suggest switching to cpuEvaulator to get releases out, then revisit TBB as a followup optimisation step.

2021-03-15 14:56 UTC, dedoardo commented on plugin/hdCycles/meshRefiner.cpp
> +#include <opensubdiv/osd/tbbEvaluator.h>
@skwerner True, I should have pointed out that I had to build opensubdiv with TBB support. I think it's a chance that the houdini variants have it. The `rez_deps` file always specifies `NO_TBB = 1` but some package along the way does `FindPackage(TBB)` and the opensubdiv cmake picks it up [because it's checking for `TBB_FOUND`](https://github.com/tangent-opensource/hdcycles/pull/88).

2021-03-16 18:57 UTC, merged